void objc_msgSend() {}
void objc_msgSend_stret() {}
void objc_msgSendSuper2() {}
void objc_getProperty() {}
void objc_setProperty() {}
void objc_copyStruct() {}
void objc_sync_enter() {}
void objc_sync_exit() {}
void sel_registerName() {}
void _Block_object_dispose() {}
void OBJC_CLASS_$__touchHLE_AppPickerDelegate() {}
void OBJC_METACLASS_$__touchHLE_AppPickerDelegate() {}
void OBJC_CLASS_$_CAAnimation() {}
void OBJC_METACLASS_$_CAAnimation() {}
void OBJC_CLASS_$_CAPropertyAnimation() {}
void OBJC_METACLASS_$_CAPropertyAnimation() {}
void OBJC_CLASS_$_CABasicAnimation() {}
void OBJC_METACLASS_$_CABasicAnimation() {}
void OBJC_CLASS_$_CATransition() {}
void OBJC_METACLASS_$_CATransition() {}
void OBJC_CLASS_$_CAEAGLLayer() {}
void OBJC_METACLASS_$_CAEAGLLayer() {}
void OBJC_CLASS_$_CALayer() {}
void OBJC_METACLASS_$_CALayer() {}
void OBJC_CLASS_$_CAMediaTimingFunction() {}
void OBJC_METACLASS_$_CAMediaTimingFunction() {}
void OBJC_CLASS_$__touchHLE_CGDataProvider() {}
void OBJC_METACLASS_$__touchHLE_CGDataProvider() {}
void OBJC_CLASS_$__touchHLE_CGColor() {}
void OBJC_METACLASS_$__touchHLE_CGColor() {}
void OBJC_CLASS_$__touchHLE_CGColorSpace() {}
void OBJC_METACLASS_$__touchHLE_CGColorSpace() {}
void OBJC_CLASS_$__touchHLE_CGContext() {}
void OBJC_METACLASS_$__touchHLE_CGContext() {}
void OBJC_CLASS_$__touchHLE_CGImage() {}
void OBJC_METACLASS_$__touchHLE_CGImage() {}
void OBJC_CLASS_$__touchHLE_CFTimerTarget() {}
void OBJC_METACLASS_$__touchHLE_CFTimerTarget() {}
void OBJC_CLASS_$_CLLocationManager() {}
void OBJC_METACLASS_$_CLLocationManager() {}
void OBJC_CLASS_$_CLHeading() {}
void OBJC_METACLASS_$_CLHeading() {}
void OBJC_CLASS_$_GKLocalPlayer() {}
void OBJC_METACLASS_$_GKLocalPlayer() {}
void OBJC_CLASS_$_GKScore() {}
void OBJC_METACLASS_$_GKScore() {}
void OBJC_CLASS_$_NSArray() {}
void OBJC_METACLASS_$_NSArray() {}
void OBJC_CLASS_$_NSMutableArray() {}
void OBJC_METACLASS_$_NSMutableArray() {}
void OBJC_CLASS_$__touchHLE_NSArray() {}
void OBJC_METACLASS_$__touchHLE_NSArray() {}
void OBJC_CLASS_$__touchHLE_NSArray_non_retaining() {}
void OBJC_METACLASS_$__touchHLE_NSArray_non_retaining() {}
void OBJC_CLASS_$__touchHLE_NSArray_ObjectEnumerator() {}
void OBJC_METACLASS_$__touchHLE_NSArray_ObjectEnumerator() {}
void OBJC_CLASS_$__touchHLE_NSMutableArray() {}
void OBJC_METACLASS_$__touchHLE_NSMutableArray() {}
void OBJC_CLASS_$__touchHLE_NSMutableArray_non_retaining() {}
void OBJC_METACLASS_$__touchHLE_NSMutableArray_non_retaining() {}
void OBJC_CLASS_$_NSAutoreleasePool() {}
void OBJC_METACLASS_$_NSAutoreleasePool() {}
void OBJC_CLASS_$_NSBundle() {}
void OBJC_METACLASS_$_NSBundle() {}
void OBJC_CLASS_$_NSCharacterSet() {}
void OBJC_METACLASS_$_NSCharacterSet() {}
void OBJC_CLASS_$__touchHLE_NSCharacterSet() {}
void OBJC_METACLASS_$__touchHLE_NSCharacterSet() {}
void OBJC_CLASS_$_NSCoder() {}
void OBJC_METACLASS_$_NSCoder() {}
void OBJC_CLASS_$_NSData() {}
void OBJC_METACLASS_$_NSData() {}
void OBJC_CLASS_$_NSMutableData() {}
void OBJC_METACLASS_$_NSMutableData() {}
void OBJC_CLASS_$_NSDate() {}
void OBJC_METACLASS_$_NSDate() {}
void OBJC_CLASS_$_NSDateFormatter() {}
void OBJC_METACLASS_$_NSDateFormatter() {}
void OBJC_CLASS_$_NSDictionary() {}
void OBJC_METACLASS_$_NSDictionary() {}
void OBJC_CLASS_$_NSMutableDictionary() {}
void OBJC_METACLASS_$_NSMutableDictionary() {}
void OBJC_CLASS_$__touchHLE_NSDictionary() {}
void OBJC_METACLASS_$__touchHLE_NSDictionary() {}
void OBJC_CLASS_$__touchHLE_NSMutableDictionary() {}
void OBJC_METACLASS_$__touchHLE_NSMutableDictionary() {}
void OBJC_CLASS_$__touchHLE_NSMutableDictionary_non_retaining() {}
void OBJC_METACLASS_$__touchHLE_NSMutableDictionary_non_retaining() {}
void OBJC_CLASS_$_NSEnumerator() {}
void OBJC_METACLASS_$_NSEnumerator() {}
void OBJC_CLASS_$_NSError() {}
void OBJC_METACLASS_$_NSError() {}
void OBJC_CLASS_$_NSFileHandle() {}
void OBJC_METACLASS_$_NSFileHandle() {}
void OBJC_CLASS_$_NSFileManager() {}
void OBJC_METACLASS_$_NSFileManager() {}
void OBJC_CLASS_$_NSDirectoryEnumerator() {}
void OBJC_METACLASS_$_NSDirectoryEnumerator() {}
void OBJC_CLASS_$_NSKeyedUnarchiver() {}
void OBJC_METACLASS_$_NSKeyedUnarchiver() {}
void OBJC_CLASS_$_NSLocale() {}
void OBJC_METACLASS_$_NSLocale() {}
void OBJC_CLASS_$_NSLock() {}
void OBJC_METACLASS_$_NSLock() {}
void OBJC_CLASS_$_NSNotification() {}
void OBJC_METACLASS_$_NSNotification() {}
void OBJC_CLASS_$_NSNotificationCenter() {}
void OBJC_METACLASS_$_NSNotificationCenter() {}
void OBJC_CLASS_$_NSNull() {}
void OBJC_METACLASS_$_NSNull() {}
void OBJC_CLASS_$_NSObject() {}
void OBJC_METACLASS_$_NSObject() {}
void OBJC_CLASS_$_NSProcessInfo() {}
void OBJC_METACLASS_$_NSProcessInfo() {}
void OBJC_CLASS_$_NSPropertyListSerialization() {}
void OBJC_METACLASS_$_NSPropertyListSerialization() {}
void OBJC_CLASS_$_NSRunLoop() {}
void OBJC_METACLASS_$_NSRunLoop() {}
void OBJC_CLASS_$_NSScanner() {}
void OBJC_METACLASS_$_NSScanner() {}
void OBJC_CLASS_$__touchHLE_NSScanner() {}
void OBJC_METACLASS_$__touchHLE_NSScanner() {}
void OBJC_CLASS_$_NSSet() {}
void OBJC_METACLASS_$_NSSet() {}
void OBJC_CLASS_$_NSMutableSet() {}
void OBJC_METACLASS_$_NSMutableSet() {}
void OBJC_CLASS_$__touchHLE_NSSet() {}
void OBJC_METACLASS_$__touchHLE_NSSet() {}
void OBJC_CLASS_$__touchHLE_NSMutableSet() {}
void OBJC_METACLASS_$__touchHLE_NSMutableSet() {}
void OBJC_CLASS_$_NSString() {}
void OBJC_METACLASS_$_NSString() {}
void OBJC_CLASS_$_NSMutableString() {}
void OBJC_METACLASS_$_NSMutableString() {}
void OBJC_CLASS_$__touchHLE_NSString() {}
void OBJC_METACLASS_$__touchHLE_NSString() {}
void OBJC_CLASS_$__touchHLE_NSString_Static() {}
void OBJC_METACLASS_$__touchHLE_NSString_Static() {}
void OBJC_CLASS_$__touchHLE_NSString_CFConstantString_UTF8() {}
void OBJC_METACLASS_$__touchHLE_NSString_CFConstantString_UTF8() {}
void OBJC_CLASS_$__touchHLE_NSString_CFConstantString_UTF16() {}
void OBJC_METACLASS_$__touchHLE_NSString_CFConstantString_UTF16() {}
void OBJC_CLASS_$__touchHLE_NSMutableString() {}
void OBJC_METACLASS_$__touchHLE_NSMutableString() {}
void OBJC_CLASS_$_NSThread() {}
void OBJC_METACLASS_$_NSThread() {}
void OBJC_CLASS_$_NSTimer() {}
void OBJC_METACLASS_$_NSTimer() {}
void OBJC_CLASS_$_NSTimeZone() {}
void OBJC_METACLASS_$_NSTimeZone() {}
void OBJC_CLASS_$_NSURL() {}
void OBJC_METACLASS_$_NSURL() {}
void OBJC_CLASS_$_NSURLCache() {}
void OBJC_METACLASS_$_NSURLCache() {}
void OBJC_CLASS_$_NSURLConnection() {}
void OBJC_METACLASS_$_NSURLConnection() {}
void OBJC_CLASS_$_NSURLRequest() {}
void OBJC_METACLASS_$_NSURLRequest() {}
void OBJC_CLASS_$_NSMutableURLRequest() {}
void OBJC_METACLASS_$_NSMutableURLRequest() {}
void OBJC_CLASS_$_NSUserDefaults() {}
void OBJC_METACLASS_$_NSUserDefaults() {}
void OBJC_CLASS_$_NSValue() {}
void OBJC_METACLASS_$_NSValue() {}
void OBJC_CLASS_$_NSNumber() {}
void OBJC_METACLASS_$_NSNumber() {}
void OBJC_CLASS_$_NSXMLParser() {}
void OBJC_METACLASS_$_NSXMLParser() {}
void OBJC_CLASS_$_AVAudioPlayer() {}
void OBJC_METACLASS_$_AVAudioPlayer() {}
void OBJC_CLASS_$_MPMoviePlayerController() {}
void OBJC_METACLASS_$_MPMoviePlayerController() {}
void OBJC_CLASS_$_MPMusicPlayerController() {}
void OBJC_METACLASS_$_MPMusicPlayerController() {}
void OBJC_CLASS_$_MPMediaLibrary() {}
void OBJC_METACLASS_$_MPMediaLibrary() {}
void OBJC_CLASS_$_MPMediaPickerController() {}
void OBJC_METACLASS_$_MPMediaPickerController() {}
void OBJC_CLASS_$_MPMediaQuery() {}
void OBJC_METACLASS_$_MPMediaQuery() {}
void OBJC_CLASS_$_EAGLContext() {}
void OBJC_METACLASS_$_EAGLContext() {}
void OBJC_CLASS_$__touchHLE_SCNetworkReachability() {}
void OBJC_METACLASS_$__touchHLE_SCNetworkReachability() {}
void OBJC_CLASS_$_SKPaymentQueue() {}
void OBJC_METACLASS_$_SKPaymentQueue() {}
void OBJC_CLASS_$_SKProduct() {}
void OBJC_METACLASS_$_SKProduct() {}
void OBJC_CLASS_$_SKProductsRequest() {}
void OBJC_METACLASS_$_SKProductsRequest() {}
void OBJC_CLASS_$_UIAccelerometer() {}
void OBJC_METACLASS_$_UIAccelerometer() {}
void OBJC_CLASS_$_UIAcceleration() {}
void OBJC_METACLASS_$_UIAcceleration() {}
void OBJC_CLASS_$_UIActivityIndicatorView() {}
void OBJC_METACLASS_$_UIActivityIndicatorView() {}
void OBJC_CLASS_$_UIApplication() {}
void OBJC_METACLASS_$_UIApplication() {}
void OBJC_CLASS_$_UIColor() {}
void OBJC_METACLASS_$_UIColor() {}
void OBJC_CLASS_$_UICGColor() {}
void OBJC_METACLASS_$_UICGColor() {}
void OBJC_CLASS_$_UIDeviceRGBColor() {}
void OBJC_METACLASS_$_UIDeviceRGBColor() {}
void OBJC_CLASS_$__touchHLE_UIColor_Static() {}
void OBJC_METACLASS_$__touchHLE_UIColor_Static() {}
void OBJC_CLASS_$_UIDevice() {}
void OBJC_METACLASS_$_UIDevice() {}
void OBJC_CLASS_$_UIEvent() {}
void OBJC_METACLASS_$_UIEvent() {}
void OBJC_CLASS_$_UIFont() {}
void OBJC_METACLASS_$_UIFont() {}
void OBJC_CLASS_$_UIImage() {}
void OBJC_METACLASS_$_UIImage() {}
void OBJC_CLASS_$_UIImagePickerController() {}
void OBJC_METACLASS_$_UIImagePickerController() {}
void OBJC_CLASS_$_UINib() {}
void OBJC_METACLASS_$_UINib() {}
void OBJC_CLASS_$_UIProxyObject() {}
void OBJC_METACLASS_$_UIProxyObject() {}
void OBJC_CLASS_$_UIClassSwapper() {}
void OBJC_METACLASS_$_UIClassSwapper() {}
void OBJC_CLASS_$_UIRuntimeConnection() {}
void OBJC_METACLASS_$_UIRuntimeConnection() {}
void OBJC_CLASS_$_UIRuntimeEventConnection() {}
void OBJC_METACLASS_$_UIRuntimeEventConnection() {}
void OBJC_CLASS_$_UIRuntimeOutletConnection() {}
void OBJC_METACLASS_$_UIRuntimeOutletConnection() {}
void OBJC_CLASS_$_UIResponder() {}
void OBJC_METACLASS_$_UIResponder() {}
void OBJC_CLASS_$_UIScreen() {}
void OBJC_METACLASS_$_UIScreen() {}
void OBJC_CLASS_$_UITouch() {}
void OBJC_METACLASS_$_UITouch() {}
void OBJC_CLASS_$_UIView() {}
void OBJC_METACLASS_$_UIView() {}
void OBJC_CLASS_$_UIAlertView() {}
void OBJC_METACLASS_$_UIAlertView() {}
void OBJC_CLASS_$_UIControl() {}
void OBJC_METACLASS_$_UIControl() {}
void OBJC_CLASS_$_UIButton() {}
void OBJC_METACLASS_$_UIButton() {}
void OBJC_CLASS_$_UIRoundedRectButton() {}
void OBJC_METACLASS_$_UIRoundedRectButton() {}
void OBJC_CLASS_$_UIButtonContent() {}
void OBJC_METACLASS_$_UIButtonContent() {}
void OBJC_CLASS_$_UISegmentedControl() {}
void OBJC_METACLASS_$_UISegmentedControl() {}
void OBJC_CLASS_$_UISegment() {}
void OBJC_METACLASS_$_UISegment() {}
void OBJC_CLASS_$_UISlider() {}
void OBJC_METACLASS_$_UISlider() {}
void OBJC_CLASS_$_UITextField() {}
void OBJC_METACLASS_$_UITextField() {}
void OBJC_CLASS_$_UISwitch() {}
void OBJC_METACLASS_$_UISwitch() {}
void OBJC_CLASS_$_UIImageView() {}
void OBJC_METACLASS_$_UIImageView() {}
void OBJC_CLASS_$_UILabel() {}
void OBJC_METACLASS_$_UILabel() {}
void OBJC_CLASS_$_UIPickerView() {}
void OBJC_METACLASS_$_UIPickerView() {}
void OBJC_CLASS_$_UIScrollView() {}
void OBJC_METACLASS_$_UIScrollView() {}
void OBJC_CLASS_$_UITextView() {}
void OBJC_METACLASS_$_UITextView() {}
void OBJC_CLASS_$_UIWebView() {}
void OBJC_METACLASS_$_UIWebView() {}
void OBJC_CLASS_$_UIWindow() {}
void OBJC_METACLASS_$_UIWindow() {}
void OBJC_CLASS_$_UIViewController() {}
void OBJC_METACLASS_$_UIViewController() {}
void OBJC_CLASS_$_UINavigationController() {}
void OBJC_METACLASS_$_UINavigationController() {}
void _objc_empty_cache() {}
void _objc_empty_vtable() {}
